# Configuration file for use of a custom toolchain
#
# (c) Koheron

# Target host
cross-compile: arm-linux-gnueabihf

devices:
    # Core devices
    - ../devices/dev_mem.yaml
    - ../tmp/zynq-sdk/middleware/drivers/xadc.hpp
    - ../tmp/zynq-sdk/middleware/drivers/gpio.hpp
    - ../tmp/zynq-sdk/middleware/drivers/oscillo.hpp
    
    # Misc
    - ../tmp/zynq-sdk/middleware/tests/tests.hpp
    - ../tmp/zynq-sdk/middleware/misc/init_tasks.hpp

