# Configuration file using a specific toolchain
#
# (c) Koheron

# Target host
cross-compile: arm-linux-gnueabihf

devices:
    # Core devices
    - ../devices/dev_mem.yaml
    
    # Misc
    - ../middleware/tests/tests.hpp
    - ../middleware/misc/init_tasks.hpp

