# Configuration file for ARM/Ubuntu
#
# (c) Koheron

# Target host
host: armhf

devices:
    # Core devices
    - ../devices/dev_mem.yaml
    
    # Misc
    - ../tmp/zynq-sdk/middleware/tests/tests.hpp
    - ../tmp/zynq-sdk/middleware/misc/init_tasks.hpp

