# Configuration file using a specific toolchain
#
# (c) Koheron

# Target host
cross-compile: arm-linux-gnueabihf-

devices:
    - ../middleware/drivers/device_memory.hpp
    - ../middleware/tests.hpp
