# Config for running tests on localhost
# To be compiled on the local computer
#
# Run a single threaded server with TCP connection
#
# (c) Koheron

# Executable name
server-name: kserverd

cross-compile: ""

arch_flags:
  - march=native

defines:
  - RELEASE_KSERVER
  - KSERVER_HAS_THREADS=0
  - KSERVER_HAS_TCP=1
  - KSERVER_HAS_WEBSOCKET=0
  - KSERVER_HAS_UNIX_SOCKET=0

debug:
  status: no # set to yes to compile in debug mode
  flags:
    - rdynamic
    - g

optimization_flags:
  - O3

devices:
    - tests/tests.hpp
    - tests/benchmarks.hpp
    - tests/exception_tests.hpp
    - tests/uses_context.hpp