# Config the server for running tests on localhost
#
# To be compiled on the local computer
#
# (c) Koheron

# Local config do not contain dev_mem

# Target host
host: local

devices:
    - ../drivers/tests.hpp
    - ../drivers/tuple_tests.hpp
    #- ../drivers/eigen_tests.hpp

